// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YOBA_LibraryData.DAL;

namespace YOBA_LibraryData.DAL.Migrations
{
    [DbContext(typeof(YOBAContext))]
    [Migration("20200129203058_SecondOne")]
    partial class SecondOne
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YOBA_LibraryData.BLL.Entities.Finance.Expence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("LastModified");

                    b.Property<string>("LastModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Expences");
                });

            modelBuilder.Entity("YOBA_LibraryData.BLL.Entities.Finance.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("LastModified");

                    b.Property<string>("LastModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("YOBA_LibraryData.BLL.Entities.Finance.Tax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("LastModified");

                    b.Property<string>("LastModifiedBy");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double>("Percent");

                    b.HasKey("Id");

                    b.ToTable("Taxes");
                });

            modelBuilder.Entity("YOBA_LibraryData.BLL.Entities.Sell.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("CustomerEmail")
                        .IsRequired();

                    b.Property<string>("CustomerLastName")
                        .IsRequired();

                    b.Property<string>("CustomerName")
                        .IsRequired();

                    b.Property<DateTime?>("LastModified");

                    b.Property<string>("LastModifiedBy");

                    b.Property<string>("TelephoneNumber");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("YOBA_LibraryData.BLL.Entities.Sell.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<int?>("CustomerId");

                    b.Property<DateTime?>("LastModified");

                    b.Property<string>("LastModifiedBy");

                    b.Property<int>("ManagerEmployeeId");

                    b.Property<string>("OrderIdentity");

                    b.Property<decimal>("OrderSum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderTime");

                    b.Property<bool>("Paid");

                    b.Property<int>("ReceiptId");

                    b.Property<bool>("Shipped");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ManagerEmployeeId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("YOBA_LibraryData.BLL.Entities.Sell.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<int?>("CusmoterCustomerId");

                    b.Property<string>("IdentialPayNumber")
                        .IsRequired();

                    b.Property<DateTime?>("LastModified");

                    b.Property<string>("LastModifiedBy");

                    b.Property<int?>("OrderId");

                    b.Property<DateTime>("PayTime");

                    b.Property<int?>("SupplierId");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CusmoterCustomerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("YOBA_LibraryData.BLL.Entities.Staff.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BranchName")
                        .IsRequired();

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("LastModified");

                    b.Property<string>("LastModifiedBy");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("YOBA_LibraryData.BLL.Entities.Staff.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BranchId");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("LastModified");

                    b.Property<string>("LastModifiedBy");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Position")
                        .IsRequired();

                    b.Property<decimal>("Sallery")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired();

                    b.HasKey("EmployeeId");

                    b.HasIndex("BranchId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("YOBA_LibraryData.BLL.Entities.Supply.Receipt", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cost");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("DocumentNumber")
                        .IsRequired();

                    b.Property<DateTime?>("LastModified");

                    b.Property<string>("LastModifiedBy");

                    b.Property<bool>("Paid");

                    b.Property<decimal?>("Price");

                    b.Property<string>("ReceiptName")
                        .IsRequired();

                    b.Property<decimal>("ReceiptValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Shipped");

                    b.Property<int?>("SupplierId");

                    b.Property<int?>("WareHouseId");

                    b.HasKey("ReceiptId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("WareHouseId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("YOBA_LibraryData.BLL.Entities.Supply.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("LastModified");

                    b.Property<string>("LastModifiedBy");

                    b.Property<string>("SupplierName")
                        .IsRequired();

                    b.Property<string>("TelephoneNumber");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("YOBA_LibraryData.BLL.Entities.Supply.WareHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("LastModified");

                    b.Property<string>("LastModifiedBy");

                    b.Property<bool>("ProductOportunity");

                    b.Property<int?>("StockManEmployeeId");

                    b.Property<string>("WareHouseName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("StockManEmployeeId");

                    b.ToTable("WareHouses");
                });

            modelBuilder.Entity("YOBA_LibraryData.DAL.Entities.UserLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Message");

                    b.Property<string>("ObjectMessage");

                    b.Property<DateTime>("Time");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("ClientLogs");
                });

            modelBuilder.Entity("YOBA_LibraryData.BLL.Entities.Sell.Order", b =>
                {
                    b.HasOne("YOBA_LibraryData.BLL.Entities.Sell.Customer", "Customer")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("CustomerId");

                    b.HasOne("YOBA_LibraryData.BLL.Entities.Staff.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("YOBA_LibraryData.BLL.Entities.Supply.Receipt", "Receipt")
                        .WithMany()
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("YOBA_LibraryData.BLL.Entities.Sell.Payment", b =>
                {
                    b.HasOne("YOBA_LibraryData.BLL.Entities.Sell.Customer", "Cusmoter")
                        .WithMany("Payments")
                        .HasForeignKey("CusmoterCustomerId");

                    b.HasOne("YOBA_LibraryData.BLL.Entities.Sell.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.HasOne("YOBA_LibraryData.BLL.Entities.Supply.Supplier")
                        .WithMany("Payments")
                        .HasForeignKey("SupplierId");
                });

            modelBuilder.Entity("YOBA_LibraryData.BLL.Entities.Staff.Employee", b =>
                {
                    b.HasOne("YOBA_LibraryData.BLL.Entities.Staff.Branch", "Branch")
                        .WithMany("Employees")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("YOBA_LibraryData.BLL.Entities.Supply.Receipt", b =>
                {
                    b.HasOne("YOBA_LibraryData.BLL.Entities.Supply.Supplier")
                        .WithMany("Entrances")
                        .HasForeignKey("SupplierId");

                    b.HasOne("YOBA_LibraryData.BLL.Entities.Supply.WareHouse")
                        .WithMany("Receipts")
                        .HasForeignKey("WareHouseId");
                });

            modelBuilder.Entity("YOBA_LibraryData.BLL.Entities.Supply.WareHouse", b =>
                {
                    b.HasOne("YOBA_LibraryData.BLL.Entities.Staff.Employee", "StockMan")
                        .WithMany()
                        .HasForeignKey("StockManEmployeeId");
                });
#pragma warning restore 612, 618
        }
    }
}
